-- Backfill ISO 3166-1 alpha-2 codes where country was stored as a display name.

UPDATE "User" SET country = 'AF' WHERE country = 'Afghanistan';
UPDATE "Order" SET country = 'AF' WHERE country = 'Afghanistan';
UPDATE "User" SET country = 'AX' WHERE country = 'Åland Islands';
UPDATE "Order" SET country = 'AX' WHERE country = 'Åland Islands';
UPDATE "User" SET country = 'AL' WHERE country = 'Albania';
UPDATE "Order" SET country = 'AL' WHERE country = 'Albania';
UPDATE "User" SET country = 'DZ' WHERE country = 'Algeria';
UPDATE "Order" SET country = 'DZ' WHERE country = 'Algeria';
UPDATE "User" SET country = 'AS' WHERE country = 'American Samoa';
UPDATE "Order" SET country = 'AS' WHERE country = 'American Samoa';
UPDATE "User" SET country = 'AD' WHERE country = 'Andorra';
UPDATE "Order" SET country = 'AD' WHERE country = 'Andorra';
UPDATE "User" SET country = 'AO' WHERE country = 'Angola';
UPDATE "Order" SET country = 'AO' WHERE country = 'Angola';
UPDATE "User" SET country = 'AI' WHERE country = 'Anguilla';
UPDATE "Order" SET country = 'AI' WHERE country = 'Anguilla';
UPDATE "User" SET country = 'AQ' WHERE country = 'Antarctica';
UPDATE "Order" SET country = 'AQ' WHERE country = 'Antarctica';
UPDATE "User" SET country = 'AG' WHERE country = 'Antigua and Barbuda';
UPDATE "Order" SET country = 'AG' WHERE country = 'Antigua and Barbuda';
UPDATE "User" SET country = 'AR' WHERE country = 'Argentina';
UPDATE "Order" SET country = 'AR' WHERE country = 'Argentina';
UPDATE "User" SET country = 'AM' WHERE country = 'Armenia';
UPDATE "Order" SET country = 'AM' WHERE country = 'Armenia';
UPDATE "User" SET country = 'AW' WHERE country = 'Aruba';
UPDATE "Order" SET country = 'AW' WHERE country = 'Aruba';
UPDATE "User" SET country = 'AU' WHERE country = 'Australia';
UPDATE "Order" SET country = 'AU' WHERE country = 'Australia';
UPDATE "User" SET country = 'AT' WHERE country = 'Austria';
UPDATE "Order" SET country = 'AT' WHERE country = 'Austria';
UPDATE "User" SET country = 'AZ' WHERE country = 'Azerbaijan';
UPDATE "Order" SET country = 'AZ' WHERE country = 'Azerbaijan';
UPDATE "User" SET country = 'BS' WHERE country = 'Bahamas';
UPDATE "Order" SET country = 'BS' WHERE country = 'Bahamas';
UPDATE "User" SET country = 'BH' WHERE country = 'Bahrain';
UPDATE "Order" SET country = 'BH' WHERE country = 'Bahrain';
UPDATE "User" SET country = 'BD' WHERE country = 'Bangladesh';
UPDATE "Order" SET country = 'BD' WHERE country = 'Bangladesh';
UPDATE "User" SET country = 'BB' WHERE country = 'Barbados';
UPDATE "Order" SET country = 'BB' WHERE country = 'Barbados';
UPDATE "User" SET country = 'BY' WHERE country = 'Belarus';
UPDATE "Order" SET country = 'BY' WHERE country = 'Belarus';
UPDATE "User" SET country = 'BE' WHERE country = 'Belgium';
UPDATE "Order" SET country = 'BE' WHERE country = 'Belgium';
UPDATE "User" SET country = 'BZ' WHERE country = 'Belize';
UPDATE "Order" SET country = 'BZ' WHERE country = 'Belize';
UPDATE "User" SET country = 'BJ' WHERE country = 'Benin';
UPDATE "Order" SET country = 'BJ' WHERE country = 'Benin';
UPDATE "User" SET country = 'BM' WHERE country = 'Bermuda';
UPDATE "Order" SET country = 'BM' WHERE country = 'Bermuda';
UPDATE "User" SET country = 'BT' WHERE country = 'Bhutan';
UPDATE "Order" SET country = 'BT' WHERE country = 'Bhutan';
UPDATE "User" SET country = 'BO' WHERE country = 'Bolivia';
UPDATE "Order" SET country = 'BO' WHERE country = 'Bolivia';
UPDATE "User" SET country = 'BA' WHERE country = 'Bosnia and Herzegovina';
UPDATE "Order" SET country = 'BA' WHERE country = 'Bosnia and Herzegovina';
UPDATE "User" SET country = 'BW' WHERE country = 'Botswana';
UPDATE "Order" SET country = 'BW' WHERE country = 'Botswana';
UPDATE "User" SET country = 'BV' WHERE country = 'Bouvet Island';
UPDATE "Order" SET country = 'BV' WHERE country = 'Bouvet Island';
UPDATE "User" SET country = 'BR' WHERE country = 'Brazil';
UPDATE "Order" SET country = 'BR' WHERE country = 'Brazil';
UPDATE "User" SET country = 'IO' WHERE country = 'British Indian Ocean Territory';
UPDATE "Order" SET country = 'IO' WHERE country = 'British Indian Ocean Territory';
UPDATE "User" SET country = 'BN' WHERE country = 'Brunei Darussalam';
UPDATE "Order" SET country = 'BN' WHERE country = 'Brunei Darussalam';
UPDATE "User" SET country = 'BG' WHERE country = 'Bulgaria';
UPDATE "Order" SET country = 'BG' WHERE country = 'Bulgaria';
UPDATE "User" SET country = 'BF' WHERE country = 'Burkina Faso';
UPDATE "Order" SET country = 'BF' WHERE country = 'Burkina Faso';
UPDATE "User" SET country = 'BI' WHERE country = 'Burundi';
UPDATE "Order" SET country = 'BI' WHERE country = 'Burundi';
UPDATE "User" SET country = 'CV' WHERE country = 'Cabo Verde';
UPDATE "Order" SET country = 'CV' WHERE country = 'Cabo Verde';
UPDATE "User" SET country = 'KH' WHERE country = 'Cambodia';
UPDATE "Order" SET country = 'KH' WHERE country = 'Cambodia';
UPDATE "User" SET country = 'CM' WHERE country = 'Cameroon';
UPDATE "Order" SET country = 'CM' WHERE country = 'Cameroon';
UPDATE "User" SET country = 'CA' WHERE country = 'Canada';
UPDATE "Order" SET country = 'CA' WHERE country = 'Canada';
UPDATE "User" SET country = 'KY' WHERE country = 'Cayman Islands';
UPDATE "Order" SET country = 'KY' WHERE country = 'Cayman Islands';
UPDATE "User" SET country = 'CF' WHERE country = 'Central African Republic';
UPDATE "Order" SET country = 'CF' WHERE country = 'Central African Republic';
UPDATE "User" SET country = 'TD' WHERE country = 'Chad';
UPDATE "Order" SET country = 'TD' WHERE country = 'Chad';
UPDATE "User" SET country = 'CL' WHERE country = 'Chile';
UPDATE "Order" SET country = 'CL' WHERE country = 'Chile';
UPDATE "User" SET country = 'CN' WHERE country = 'China';
UPDATE "Order" SET country = 'CN' WHERE country = 'China';
UPDATE "User" SET country = 'CX' WHERE country = 'Christmas Island';
UPDATE "Order" SET country = 'CX' WHERE country = 'Christmas Island';
UPDATE "User" SET country = 'CC' WHERE country = 'Cocos (Keeling) Islands';
UPDATE "Order" SET country = 'CC' WHERE country = 'Cocos (Keeling) Islands';
UPDATE "User" SET country = 'CO' WHERE country = 'Colombia';
UPDATE "Order" SET country = 'CO' WHERE country = 'Colombia';
UPDATE "User" SET country = 'KM' WHERE country = 'Comoros';
UPDATE "Order" SET country = 'KM' WHERE country = 'Comoros';
UPDATE "User" SET country = 'CG' WHERE country = 'Congo';
UPDATE "Order" SET country = 'CG' WHERE country = 'Congo';
UPDATE "User" SET country = 'CD' WHERE country = 'Congo, Democratic Republic of the';
UPDATE "Order" SET country = 'CD' WHERE country = 'Congo, Democratic Republic of the';
UPDATE "User" SET country = 'CK' WHERE country = 'Cook Islands';
UPDATE "Order" SET country = 'CK' WHERE country = 'Cook Islands';
UPDATE "User" SET country = 'CR' WHERE country = 'Costa Rica';
UPDATE "Order" SET country = 'CR' WHERE country = 'Costa Rica';
UPDATE "User" SET country = 'CI' WHERE country = 'Côte d''Ivoire';
UPDATE "Order" SET country = 'CI' WHERE country = 'Côte d''Ivoire';
UPDATE "User" SET country = 'HR' WHERE country = 'Croatia';
UPDATE "Order" SET country = 'HR' WHERE country = 'Croatia';
UPDATE "User" SET country = 'CU' WHERE country = 'Cuba';
UPDATE "Order" SET country = 'CU' WHERE country = 'Cuba';
UPDATE "User" SET country = 'CW' WHERE country = 'Curaçao';
UPDATE "Order" SET country = 'CW' WHERE country = 'Curaçao';
UPDATE "User" SET country = 'CY' WHERE country = 'Cyprus';
UPDATE "Order" SET country = 'CY' WHERE country = 'Cyprus';
UPDATE "User" SET country = 'CZ' WHERE country = 'Czechia';
UPDATE "Order" SET country = 'CZ' WHERE country = 'Czechia';
UPDATE "User" SET country = 'DK' WHERE country = 'Denmark';
UPDATE "Order" SET country = 'DK' WHERE country = 'Denmark';
UPDATE "User" SET country = 'DJ' WHERE country = 'Djibouti';
UPDATE "Order" SET country = 'DJ' WHERE country = 'Djibouti';
UPDATE "User" SET country = 'DM' WHERE country = 'Dominica';
UPDATE "Order" SET country = 'DM' WHERE country = 'Dominica';
UPDATE "User" SET country = 'DO' WHERE country = 'Dominican Republic';
UPDATE "Order" SET country = 'DO' WHERE country = 'Dominican Republic';
UPDATE "User" SET country = 'EC' WHERE country = 'Ecuador';
UPDATE "Order" SET country = 'EC' WHERE country = 'Ecuador';
UPDATE "User" SET country = 'EG' WHERE country = 'Egypt';
UPDATE "Order" SET country = 'EG' WHERE country = 'Egypt';
UPDATE "User" SET country = 'SV' WHERE country = 'El Salvador';
UPDATE "Order" SET country = 'SV' WHERE country = 'El Salvador';
UPDATE "User" SET country = 'GQ' WHERE country = 'Equatorial Guinea';
UPDATE "Order" SET country = 'GQ' WHERE country = 'Equatorial Guinea';
UPDATE "User" SET country = 'ER' WHERE country = 'Eritrea';
UPDATE "Order" SET country = 'ER' WHERE country = 'Eritrea';
UPDATE "User" SET country = 'EE' WHERE country = 'Estonia';
UPDATE "Order" SET country = 'EE' WHERE country = 'Estonia';
UPDATE "User" SET country = 'SZ' WHERE country = 'Eswatini';
UPDATE "Order" SET country = 'SZ' WHERE country = 'Eswatini';
UPDATE "User" SET country = 'ET' WHERE country = 'Ethiopia';
UPDATE "Order" SET country = 'ET' WHERE country = 'Ethiopia';
UPDATE "User" SET country = 'FK' WHERE country = 'Falkland Islands';
UPDATE "Order" SET country = 'FK' WHERE country = 'Falkland Islands';
UPDATE "User" SET country = 'FO' WHERE country = 'Faroe Islands';
UPDATE "Order" SET country = 'FO' WHERE country = 'Faroe Islands';
UPDATE "User" SET country = 'FJ' WHERE country = 'Fiji';
UPDATE "Order" SET country = 'FJ' WHERE country = 'Fiji';
UPDATE "User" SET country = 'FI' WHERE country = 'Finland';
UPDATE "Order" SET country = 'FI' WHERE country = 'Finland';
UPDATE "User" SET country = 'FR' WHERE country = 'France';
UPDATE "Order" SET country = 'FR' WHERE country = 'France';
UPDATE "User" SET country = 'GF' WHERE country = 'French Guiana';
UPDATE "Order" SET country = 'GF' WHERE country = 'French Guiana';
UPDATE "User" SET country = 'PF' WHERE country = 'French Polynesia';
UPDATE "Order" SET country = 'PF' WHERE country = 'French Polynesia';
UPDATE "User" SET country = 'TF' WHERE country = 'French Southern Territories';
UPDATE "Order" SET country = 'TF' WHERE country = 'French Southern Territories';
UPDATE "User" SET country = 'GA' WHERE country = 'Gabon';
UPDATE "Order" SET country = 'GA' WHERE country = 'Gabon';
UPDATE "User" SET country = 'GM' WHERE country = 'Gambia';
UPDATE "Order" SET country = 'GM' WHERE country = 'Gambia';
UPDATE "User" SET country = 'GE' WHERE country = 'Georgia';
UPDATE "Order" SET country = 'GE' WHERE country = 'Georgia';
UPDATE "User" SET country = 'DE' WHERE country = 'Germany';
UPDATE "Order" SET country = 'DE' WHERE country = 'Germany';
UPDATE "User" SET country = 'GH' WHERE country = 'Ghana';
UPDATE "Order" SET country = 'GH' WHERE country = 'Ghana';
UPDATE "User" SET country = 'GI' WHERE country = 'Gibraltar';
UPDATE "Order" SET country = 'GI' WHERE country = 'Gibraltar';
UPDATE "User" SET country = 'GR' WHERE country = 'Greece';
UPDATE "Order" SET country = 'GR' WHERE country = 'Greece';
UPDATE "User" SET country = 'GL' WHERE country = 'Greenland';
UPDATE "Order" SET country = 'GL' WHERE country = 'Greenland';
UPDATE "User" SET country = 'GD' WHERE country = 'Grenada';
UPDATE "Order" SET country = 'GD' WHERE country = 'Grenada';
UPDATE "User" SET country = 'GP' WHERE country = 'Guadeloupe';
UPDATE "Order" SET country = 'GP' WHERE country = 'Guadeloupe';
UPDATE "User" SET country = 'GU' WHERE country = 'Guam';
UPDATE "Order" SET country = 'GU' WHERE country = 'Guam';
UPDATE "User" SET country = 'GT' WHERE country = 'Guatemala';
UPDATE "Order" SET country = 'GT' WHERE country = 'Guatemala';
UPDATE "User" SET country = 'GG' WHERE country = 'Guernsey';
UPDATE "Order" SET country = 'GG' WHERE country = 'Guernsey';
UPDATE "User" SET country = 'GN' WHERE country = 'Guinea';
UPDATE "Order" SET country = 'GN' WHERE country = 'Guinea';
UPDATE "User" SET country = 'GW' WHERE country = 'Guinea-Bissau';
UPDATE "Order" SET country = 'GW' WHERE country = 'Guinea-Bissau';
UPDATE "User" SET country = 'GY' WHERE country = 'Guyana';
UPDATE "Order" SET country = 'GY' WHERE country = 'Guyana';
UPDATE "User" SET country = 'HT' WHERE country = 'Haiti';
UPDATE "Order" SET country = 'HT' WHERE country = 'Haiti';
UPDATE "User" SET country = 'HM' WHERE country = 'Heard Island and McDonald Islands';
UPDATE "Order" SET country = 'HM' WHERE country = 'Heard Island and McDonald Islands';
UPDATE "User" SET country = 'VA' WHERE country = 'Holy See';
UPDATE "Order" SET country = 'VA' WHERE country = 'Holy See';
UPDATE "User" SET country = 'HN' WHERE country = 'Honduras';
UPDATE "Order" SET country = 'HN' WHERE country = 'Honduras';
UPDATE "User" SET country = 'HK' WHERE country = 'Hong Kong';
UPDATE "Order" SET country = 'HK' WHERE country = 'Hong Kong';
UPDATE "User" SET country = 'HU' WHERE country = 'Hungary';
UPDATE "Order" SET country = 'HU' WHERE country = 'Hungary';
UPDATE "User" SET country = 'IS' WHERE country = 'Iceland';
UPDATE "Order" SET country = 'IS' WHERE country = 'Iceland';
UPDATE "User" SET country = 'IN' WHERE country = 'India';
UPDATE "Order" SET country = 'IN' WHERE country = 'India';
UPDATE "User" SET country = 'ID' WHERE country = 'Indonesia';
UPDATE "Order" SET country = 'ID' WHERE country = 'Indonesia';
UPDATE "User" SET country = 'IR' WHERE country = 'Iran';
UPDATE "Order" SET country = 'IR' WHERE country = 'Iran';
UPDATE "User" SET country = 'IQ' WHERE country = 'Iraq';
UPDATE "Order" SET country = 'IQ' WHERE country = 'Iraq';
UPDATE "User" SET country = 'IE' WHERE country = 'Ireland';
UPDATE "Order" SET country = 'IE' WHERE country = 'Ireland';
UPDATE "User" SET country = 'IM' WHERE country = 'Isle of Man';
UPDATE "Order" SET country = 'IM' WHERE country = 'Isle of Man';
UPDATE "User" SET country = 'IL' WHERE country = 'Israel';
UPDATE "Order" SET country = 'IL' WHERE country = 'Israel';
UPDATE "User" SET country = 'IT' WHERE country = 'Italy';
UPDATE "Order" SET country = 'IT' WHERE country = 'Italy';
UPDATE "User" SET country = 'JM' WHERE country = 'Jamaica';
UPDATE "Order" SET country = 'JM' WHERE country = 'Jamaica';
UPDATE "User" SET country = 'JP' WHERE country = 'Japan';
UPDATE "Order" SET country = 'JP' WHERE country = 'Japan';
UPDATE "User" SET country = 'JE' WHERE country = 'Jersey';
UPDATE "Order" SET country = 'JE' WHERE country = 'Jersey';
UPDATE "User" SET country = 'JO' WHERE country = 'Jordan';
UPDATE "Order" SET country = 'JO' WHERE country = 'Jordan';
UPDATE "User" SET country = 'KZ' WHERE country = 'Kazakhstan';
UPDATE "Order" SET country = 'KZ' WHERE country = 'Kazakhstan';
UPDATE "User" SET country = 'KE' WHERE country = 'Kenya';
UPDATE "Order" SET country = 'KE' WHERE country = 'Kenya';
UPDATE "User" SET country = 'KI' WHERE country = 'Kiribati';
UPDATE "Order" SET country = 'KI' WHERE country = 'Kiribati';
UPDATE "User" SET country = 'KP' WHERE country = 'Korea, Democratic People''s Republic of';
UPDATE "Order" SET country = 'KP' WHERE country = 'Korea, Democratic People''s Republic of';
UPDATE "User" SET country = 'KR' WHERE country = 'Korea, Republic of';
UPDATE "Order" SET country = 'KR' WHERE country = 'Korea, Republic of';
UPDATE "User" SET country = 'KW' WHERE country = 'Kuwait';
UPDATE "Order" SET country = 'KW' WHERE country = 'Kuwait';
UPDATE "User" SET country = 'KG' WHERE country = 'Kyrgyzstan';
UPDATE "Order" SET country = 'KG' WHERE country = 'Kyrgyzstan';
UPDATE "User" SET country = 'LA' WHERE country = 'Lao People''s Democratic Republic';
UPDATE "Order" SET country = 'LA' WHERE country = 'Lao People''s Democratic Republic';
UPDATE "User" SET country = 'LV' WHERE country = 'Latvia';
UPDATE "Order" SET country = 'LV' WHERE country = 'Latvia';
UPDATE "User" SET country = 'LB' WHERE country = 'Lebanon';
UPDATE "Order" SET country = 'LB' WHERE country = 'Lebanon';
UPDATE "User" SET country = 'LS' WHERE country = 'Lesotho';
UPDATE "Order" SET country = 'LS' WHERE country = 'Lesotho';
UPDATE "User" SET country = 'LR' WHERE country = 'Liberia';
UPDATE "Order" SET country = 'LR' WHERE country = 'Liberia';
UPDATE "User" SET country = 'LY' WHERE country = 'Libya';
UPDATE "Order" SET country = 'LY' WHERE country = 'Libya';
UPDATE "User" SET country = 'LI' WHERE country = 'Liechtenstein';
UPDATE "Order" SET country = 'LI' WHERE country = 'Liechtenstein';
UPDATE "User" SET country = 'LT' WHERE country = 'Lithuania';
UPDATE "Order" SET country = 'LT' WHERE country = 'Lithuania';
UPDATE "User" SET country = 'LU' WHERE country = 'Luxembourg';
UPDATE "Order" SET country = 'LU' WHERE country = 'Luxembourg';
UPDATE "User" SET country = 'MO' WHERE country = 'Macao';
UPDATE "Order" SET country = 'MO' WHERE country = 'Macao';
UPDATE "User" SET country = 'MG' WHERE country = 'Madagascar';
UPDATE "Order" SET country = 'MG' WHERE country = 'Madagascar';
UPDATE "User" SET country = 'MW' WHERE country = 'Malawi';
UPDATE "Order" SET country = 'MW' WHERE country = 'Malawi';
UPDATE "User" SET country = 'MY' WHERE country = 'Malaysia';
UPDATE "Order" SET country = 'MY' WHERE country = 'Malaysia';
UPDATE "User" SET country = 'MV' WHERE country = 'Maldives';
UPDATE "Order" SET country = 'MV' WHERE country = 'Maldives';
UPDATE "User" SET country = 'ML' WHERE country = 'Mali';
UPDATE "Order" SET country = 'ML' WHERE country = 'Mali';
UPDATE "User" SET country = 'MT' WHERE country = 'Malta';
UPDATE "Order" SET country = 'MT' WHERE country = 'Malta';
UPDATE "User" SET country = 'MH' WHERE country = 'Marshall Islands';
UPDATE "Order" SET country = 'MH' WHERE country = 'Marshall Islands';
UPDATE "User" SET country = 'MQ' WHERE country = 'Martinique';
UPDATE "Order" SET country = 'MQ' WHERE country = 'Martinique';
UPDATE "User" SET country = 'MR' WHERE country = 'Mauritania';
UPDATE "Order" SET country = 'MR' WHERE country = 'Mauritania';
UPDATE "User" SET country = 'MU' WHERE country = 'Mauritius';
UPDATE "Order" SET country = 'MU' WHERE country = 'Mauritius';
UPDATE "User" SET country = 'YT' WHERE country = 'Mayotte';
UPDATE "Order" SET country = 'YT' WHERE country = 'Mayotte';
UPDATE "User" SET country = 'MX' WHERE country = 'Mexico';
UPDATE "Order" SET country = 'MX' WHERE country = 'Mexico';
UPDATE "User" SET country = 'FM' WHERE country = 'Micronesia';
UPDATE "Order" SET country = 'FM' WHERE country = 'Micronesia';
UPDATE "User" SET country = 'MD' WHERE country = 'Moldova';
UPDATE "Order" SET country = 'MD' WHERE country = 'Moldova';
UPDATE "User" SET country = 'MC' WHERE country = 'Monaco';
UPDATE "Order" SET country = 'MC' WHERE country = 'Monaco';
UPDATE "User" SET country = 'MN' WHERE country = 'Mongolia';
UPDATE "Order" SET country = 'MN' WHERE country = 'Mongolia';
UPDATE "User" SET country = 'ME' WHERE country = 'Montenegro';
UPDATE "Order" SET country = 'ME' WHERE country = 'Montenegro';
UPDATE "User" SET country = 'MS' WHERE country = 'Montserrat';
UPDATE "Order" SET country = 'MS' WHERE country = 'Montserrat';
UPDATE "User" SET country = 'MA' WHERE country = 'Morocco';
UPDATE "Order" SET country = 'MA' WHERE country = 'Morocco';
UPDATE "User" SET country = 'MZ' WHERE country = 'Mozambique';
UPDATE "Order" SET country = 'MZ' WHERE country = 'Mozambique';
UPDATE "User" SET country = 'MM' WHERE country = 'Myanmar';
UPDATE "Order" SET country = 'MM' WHERE country = 'Myanmar';
UPDATE "User" SET country = 'NA' WHERE country = 'Namibia';
UPDATE "Order" SET country = 'NA' WHERE country = 'Namibia';
UPDATE "User" SET country = 'NR' WHERE country = 'Nauru';
UPDATE "Order" SET country = 'NR' WHERE country = 'Nauru';
UPDATE "User" SET country = 'NP' WHERE country = 'Nepal';
UPDATE "Order" SET country = 'NP' WHERE country = 'Nepal';
UPDATE "User" SET country = 'NL' WHERE country = 'Netherlands';
UPDATE "Order" SET country = 'NL' WHERE country = 'Netherlands';
UPDATE "User" SET country = 'NC' WHERE country = 'New Caledonia';
UPDATE "Order" SET country = 'NC' WHERE country = 'New Caledonia';
UPDATE "User" SET country = 'NZ' WHERE country = 'New Zealand';
UPDATE "Order" SET country = 'NZ' WHERE country = 'New Zealand';
UPDATE "User" SET country = 'NI' WHERE country = 'Nicaragua';
UPDATE "Order" SET country = 'NI' WHERE country = 'Nicaragua';
UPDATE "User" SET country = 'NE' WHERE country = 'Niger';
UPDATE "Order" SET country = 'NE' WHERE country = 'Niger';
UPDATE "User" SET country = 'NG' WHERE country = 'Nigeria';
UPDATE "Order" SET country = 'NG' WHERE country = 'Nigeria';
UPDATE "User" SET country = 'NU' WHERE country = 'Niue';
UPDATE "Order" SET country = 'NU' WHERE country = 'Niue';
UPDATE "User" SET country = 'NF' WHERE country = 'Norfolk Island';
UPDATE "Order" SET country = 'NF' WHERE country = 'Norfolk Island';
UPDATE "User" SET country = 'MK' WHERE country = 'North Macedonia';
UPDATE "Order" SET country = 'MK' WHERE country = 'North Macedonia';
UPDATE "User" SET country = 'MP' WHERE country = 'Northern Mariana Islands';
UPDATE "Order" SET country = 'MP' WHERE country = 'Northern Mariana Islands';
UPDATE "User" SET country = 'NO' WHERE country = 'Norway';
UPDATE "Order" SET country = 'NO' WHERE country = 'Norway';
UPDATE "User" SET country = 'OM' WHERE country = 'Oman';
UPDATE "Order" SET country = 'OM' WHERE country = 'Oman';
UPDATE "User" SET country = 'PK' WHERE country = 'Pakistan';
UPDATE "Order" SET country = 'PK' WHERE country = 'Pakistan';
UPDATE "User" SET country = 'PW' WHERE country = 'Palau';
UPDATE "Order" SET country = 'PW' WHERE country = 'Palau';
UPDATE "User" SET country = 'PS' WHERE country = 'Palestine';
UPDATE "Order" SET country = 'PS' WHERE country = 'Palestine';
UPDATE "User" SET country = 'PA' WHERE country = 'Panama';
UPDATE "Order" SET country = 'PA' WHERE country = 'Panama';
UPDATE "User" SET country = 'PG' WHERE country = 'Papua New Guinea';
UPDATE "Order" SET country = 'PG' WHERE country = 'Papua New Guinea';
UPDATE "User" SET country = 'PY' WHERE country = 'Paraguay';
UPDATE "Order" SET country = 'PY' WHERE country = 'Paraguay';
UPDATE "User" SET country = 'PE' WHERE country = 'Peru';
UPDATE "Order" SET country = 'PE' WHERE country = 'Peru';
UPDATE "User" SET country = 'PH' WHERE country = 'Philippines';
UPDATE "Order" SET country = 'PH' WHERE country = 'Philippines';
UPDATE "User" SET country = 'PN' WHERE country = 'Pitcairn';
UPDATE "Order" SET country = 'PN' WHERE country = 'Pitcairn';
UPDATE "User" SET country = 'PL' WHERE country = 'Poland';
UPDATE "Order" SET country = 'PL' WHERE country = 'Poland';
UPDATE "User" SET country = 'PT' WHERE country = 'Portugal';
UPDATE "Order" SET country = 'PT' WHERE country = 'Portugal';
UPDATE "User" SET country = 'PR' WHERE country = 'Puerto Rico';
UPDATE "Order" SET country = 'PR' WHERE country = 'Puerto Rico';
UPDATE "User" SET country = 'QA' WHERE country = 'Qatar';
UPDATE "Order" SET country = 'QA' WHERE country = 'Qatar';
UPDATE "User" SET country = 'RE' WHERE country = 'Réunion';
UPDATE "Order" SET country = 'RE' WHERE country = 'Réunion';
UPDATE "User" SET country = 'RO' WHERE country = 'Romania';
UPDATE "Order" SET country = 'RO' WHERE country = 'Romania';
UPDATE "User" SET country = 'RU' WHERE country = 'Russian Federation';
UPDATE "Order" SET country = 'RU' WHERE country = 'Russian Federation';
UPDATE "User" SET country = 'RW' WHERE country = 'Rwanda';
UPDATE "Order" SET country = 'RW' WHERE country = 'Rwanda';
UPDATE "User" SET country = 'BL' WHERE country = 'Saint Barthélemy';
UPDATE "Order" SET country = 'BL' WHERE country = 'Saint Barthélemy';
UPDATE "User" SET country = 'SH' WHERE country = 'Saint Helena';
UPDATE "Order" SET country = 'SH' WHERE country = 'Saint Helena';
UPDATE "User" SET country = 'KN' WHERE country = 'Saint Kitts and Nevis';
UPDATE "Order" SET country = 'KN' WHERE country = 'Saint Kitts and Nevis';
UPDATE "User" SET country = 'LC' WHERE country = 'Saint Lucia';
UPDATE "Order" SET country = 'LC' WHERE country = 'Saint Lucia';
UPDATE "User" SET country = 'MF' WHERE country = 'Saint Martin (French part)';
UPDATE "Order" SET country = 'MF' WHERE country = 'Saint Martin (French part)';
UPDATE "User" SET country = 'PM' WHERE country = 'Saint Pierre and Miquelon';
UPDATE "Order" SET country = 'PM' WHERE country = 'Saint Pierre and Miquelon';
UPDATE "User" SET country = 'VC' WHERE country = 'Saint Vincent and the Grenadines';
UPDATE "Order" SET country = 'VC' WHERE country = 'Saint Vincent and the Grenadines';
UPDATE "User" SET country = 'WS' WHERE country = 'Samoa';
UPDATE "Order" SET country = 'WS' WHERE country = 'Samoa';
UPDATE "User" SET country = 'SM' WHERE country = 'San Marino';
UPDATE "Order" SET country = 'SM' WHERE country = 'San Marino';
UPDATE "User" SET country = 'ST' WHERE country = 'Sao Tome and Principe';
UPDATE "Order" SET country = 'ST' WHERE country = 'Sao Tome and Principe';
UPDATE "User" SET country = 'SA' WHERE country = 'Saudi Arabia';
UPDATE "Order" SET country = 'SA' WHERE country = 'Saudi Arabia';
UPDATE "User" SET country = 'SN' WHERE country = 'Senegal';
UPDATE "Order" SET country = 'SN' WHERE country = 'Senegal';
UPDATE "User" SET country = 'RS' WHERE country = 'Serbia';
UPDATE "Order" SET country = 'RS' WHERE country = 'Serbia';
UPDATE "User" SET country = 'SC' WHERE country = 'Seychelles';
UPDATE "Order" SET country = 'SC' WHERE country = 'Seychelles';
UPDATE "User" SET country = 'SL' WHERE country = 'Sierra Leone';
UPDATE "Order" SET country = 'SL' WHERE country = 'Sierra Leone';
UPDATE "User" SET country = 'SG' WHERE country = 'Singapore';
UPDATE "Order" SET country = 'SG' WHERE country = 'Singapore';
UPDATE "User" SET country = 'SX' WHERE country = 'Sint Maarten (Dutch part)';
UPDATE "Order" SET country = 'SX' WHERE country = 'Sint Maarten (Dutch part)';
UPDATE "User" SET country = 'SK' WHERE country = 'Slovakia';
UPDATE "Order" SET country = 'SK' WHERE country = 'Slovakia';
UPDATE "User" SET country = 'SI' WHERE country = 'Slovenia';
UPDATE "Order" SET country = 'SI' WHERE country = 'Slovenia';
UPDATE "User" SET country = 'SB' WHERE country = 'Solomon Islands';
UPDATE "Order" SET country = 'SB' WHERE country = 'Solomon Islands';
UPDATE "User" SET country = 'SO' WHERE country = 'Somalia';
UPDATE "Order" SET country = 'SO' WHERE country = 'Somalia';
UPDATE "User" SET country = 'ZA' WHERE country = 'South Africa';
UPDATE "Order" SET country = 'ZA' WHERE country = 'South Africa';
UPDATE "User" SET country = 'GS' WHERE country = 'South Georgia and the South Sandwich Islands';
UPDATE "Order" SET country = 'GS' WHERE country = 'South Georgia and the South Sandwich Islands';
UPDATE "User" SET country = 'SS' WHERE country = 'South Sudan';
UPDATE "Order" SET country = 'SS' WHERE country = 'South Sudan';
UPDATE "User" SET country = 'ES' WHERE country = 'Spain';
UPDATE "Order" SET country = 'ES' WHERE country = 'Spain';
UPDATE "User" SET country = 'LK' WHERE country = 'Sri Lanka';
UPDATE "Order" SET country = 'LK' WHERE country = 'Sri Lanka';
UPDATE "User" SET country = 'SD' WHERE country = 'Sudan';
UPDATE "Order" SET country = 'SD' WHERE country = 'Sudan';
UPDATE "User" SET country = 'SR' WHERE country = 'Suriname';
UPDATE "Order" SET country = 'SR' WHERE country = 'Suriname';
UPDATE "User" SET country = 'SJ' WHERE country = 'Svalbard and Jan Mayen';
UPDATE "Order" SET country = 'SJ' WHERE country = 'Svalbard and Jan Mayen';
UPDATE "User" SET country = 'SE' WHERE country = 'Sweden';
UPDATE "Order" SET country = 'SE' WHERE country = 'Sweden';
UPDATE "User" SET country = 'CH' WHERE country = 'Switzerland';
UPDATE "Order" SET country = 'CH' WHERE country = 'Switzerland';
UPDATE "User" SET country = 'SY' WHERE country = 'Syrian Arab Republic';
UPDATE "Order" SET country = 'SY' WHERE country = 'Syrian Arab Republic';
UPDATE "User" SET country = 'TW' WHERE country = 'Taiwan';
UPDATE "Order" SET country = 'TW' WHERE country = 'Taiwan';
UPDATE "User" SET country = 'TJ' WHERE country = 'Tajikistan';
UPDATE "Order" SET country = 'TJ' WHERE country = 'Tajikistan';
UPDATE "User" SET country = 'TZ' WHERE country = 'Tanzania';
UPDATE "Order" SET country = 'TZ' WHERE country = 'Tanzania';
UPDATE "User" SET country = 'TH' WHERE country = 'Thailand';
UPDATE "Order" SET country = 'TH' WHERE country = 'Thailand';
UPDATE "User" SET country = 'TL' WHERE country = 'Timor-Leste';
UPDATE "Order" SET country = 'TL' WHERE country = 'Timor-Leste';
UPDATE "User" SET country = 'TG' WHERE country = 'Togo';
UPDATE "Order" SET country = 'TG' WHERE country = 'Togo';
UPDATE "User" SET country = 'TK' WHERE country = 'Tokelau';
UPDATE "Order" SET country = 'TK' WHERE country = 'Tokelau';
UPDATE "User" SET country = 'TO' WHERE country = 'Tonga';
UPDATE "Order" SET country = 'TO' WHERE country = 'Tonga';
UPDATE "User" SET country = 'TT' WHERE country = 'Trinidad and Tobago';
UPDATE "Order" SET country = 'TT' WHERE country = 'Trinidad and Tobago';
UPDATE "User" SET country = 'TN' WHERE country = 'Tunisia';
UPDATE "Order" SET country = 'TN' WHERE country = 'Tunisia';
UPDATE "User" SET country = 'TR' WHERE country = 'Türkiye';
UPDATE "Order" SET country = 'TR' WHERE country = 'Türkiye';
UPDATE "User" SET country = 'TM' WHERE country = 'Turkmenistan';
UPDATE "Order" SET country = 'TM' WHERE country = 'Turkmenistan';
UPDATE "User" SET country = 'TC' WHERE country = 'Turks and Caicos Islands';
UPDATE "Order" SET country = 'TC' WHERE country = 'Turks and Caicos Islands';
UPDATE "User" SET country = 'TV' WHERE country = 'Tuvalu';
UPDATE "Order" SET country = 'TV' WHERE country = 'Tuvalu';
UPDATE "User" SET country = 'UG' WHERE country = 'Uganda';
UPDATE "Order" SET country = 'UG' WHERE country = 'Uganda';
UPDATE "User" SET country = 'UA' WHERE country = 'Ukraine';
UPDATE "Order" SET country = 'UA' WHERE country = 'Ukraine';
UPDATE "User" SET country = 'AE' WHERE country = 'United Arab Emirates';
UPDATE "Order" SET country = 'AE' WHERE country = 'United Arab Emirates';
UPDATE "User" SET country = 'GB' WHERE country = 'United Kingdom';
UPDATE "Order" SET country = 'GB' WHERE country = 'United Kingdom';
UPDATE "User" SET country = 'US' WHERE country = 'United States';
UPDATE "Order" SET country = 'US' WHERE country = 'United States';
UPDATE "User" SET country = 'UY' WHERE country = 'Uruguay';
UPDATE "Order" SET country = 'UY' WHERE country = 'Uruguay';
UPDATE "User" SET country = 'UZ' WHERE country = 'Uzbekistan';
UPDATE "Order" SET country = 'UZ' WHERE country = 'Uzbekistan';
UPDATE "User" SET country = 'VU' WHERE country = 'Vanuatu';
UPDATE "Order" SET country = 'VU' WHERE country = 'Vanuatu';
UPDATE "User" SET country = 'VE' WHERE country = 'Venezuela';
UPDATE "Order" SET country = 'VE' WHERE country = 'Venezuela';
UPDATE "User" SET country = 'VN' WHERE country = 'Viet Nam';
UPDATE "Order" SET country = 'VN' WHERE country = 'Viet Nam';
UPDATE "User" SET country = 'VG' WHERE country = 'Virgin Islands, British';
UPDATE "Order" SET country = 'VG' WHERE country = 'Virgin Islands, British';
UPDATE "User" SET country = 'VI' WHERE country = 'Virgin Islands, U.S.';
UPDATE "Order" SET country = 'VI' WHERE country = 'Virgin Islands, U.S.';
UPDATE "User" SET country = 'WF' WHERE country = 'Wallis and Futuna';
UPDATE "Order" SET country = 'WF' WHERE country = 'Wallis and Futuna';
UPDATE "User" SET country = 'EH' WHERE country = 'Western Sahara';
UPDATE "Order" SET country = 'EH' WHERE country = 'Western Sahara';
UPDATE "User" SET country = 'YE' WHERE country = 'Yemen';
UPDATE "Order" SET country = 'YE' WHERE country = 'Yemen';
UPDATE "User" SET country = 'ZM' WHERE country = 'Zambia';
UPDATE "Order" SET country = 'ZM' WHERE country = 'Zambia';
UPDATE "User" SET country = 'ZW' WHERE country = 'Zimbabwe';
UPDATE "Order" SET country = 'ZW' WHERE country = 'Zimbabwe';
