-- AlterEnum
ALTER TYPE "NotificationEvent" ADD VALUE 'ORG_MEMBER_REMOVED';
ALTER TYPE "NotificationEvent" ADD VALUE 'COURSE_DELETED_BY_ADMIN';
ALTER TYPE "NotificationEvent" ADD VALUE 'EMAIL_DELIVERY_FAILED';
