// ISO 3166-1 country list. `code` is alpha-2 and is what we persist on the user.
export interface Country {
  code: string;
  name: string;
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan" },
  { code: "AX", name: "Åland Islands" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AS", name: "American Samoa" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguilla" },
  { code: "AQ", name: "Antarctica" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AW", name: "Aruba" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BM", name: "Bermuda" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BV", name: "Bouvet Island" },
  { code: "BR", name: "Brazil" },
  { code: "IO", name: "British Indian Ocean Territory" },
  { code: "BN", name: "Brunei Darussalam" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "CV", name: "Cabo Verde" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "KY", name: "Cayman Islands" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CX", name: "Christmas Island" },
  { code: "CC", name: "Cocos (Keeling) Islands" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "Congo, Democratic Republic of the" },
  { code: "CK", name: "Cook Islands" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CW", name: "Curaçao" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czechia" },
  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },
  { code: "FK", name: "Falkland Islands" },
  { code: "FO", name: "Faroe Islands" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GF", name: "French Guiana" },
  { code: "PF", name: "French Polynesia" },
  { code: "TF", name: "French Southern Territories" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" },
  { code: "GR", name: "Greece" },
  { code: "GL", name: "Greenland" },
  { code: "GD", name: "Grenada" },
  { code: "GP", name: "Guadeloupe" },
  { code: "GU", name: "Guam" },
  { code: "GT", name: "Guatemala" },
  { code: "GG", name: "Guernsey" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HM", name: "Heard Island and McDonald Islands" },
  { code: "VA", name: "Holy See" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong Kong" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IM", name: "Isle of Man" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JE", name: "Jersey" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KP", name: "Korea, Democratic People's Republic of" },
  { code: "KR", name: "Korea, Republic of" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Lao People's Democratic Republic" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MO", name: "Macao" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MQ", name: "Martinique" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "YT", name: "Mayotte" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MS", name: "Montserrat" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NC", name: "New Caledonia" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "NU", name: "Niue" },
  { code: "NF", name: "Norfolk Island" },
  { code: "MK", name: "North Macedonia" },
  { code: "MP", name: "Northern Mariana Islands" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestine" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PN", name: "Pitcairn" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "PR", name: "Puerto Rico" },
  { code: "QA", name: "Qatar" },
  { code: "RE", name: "Réunion" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russian Federation" },
  { code: "RW", name: "Rwanda" },
  { code: "BL", name: "Saint Barthélemy" },
  { code: "SH", name: "Saint Helena" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "MF", name: "Saint Martin (French part)" },
  { code: "PM", name: "Saint Pierre and Miquelon" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "Sao Tome and Principe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SX", name: "Sint Maarten (Dutch part)" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands" },
  { code: "SS", name: "South Sudan" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SJ", name: "Svalbard and Jan Mayen" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syrian Arab Republic" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TK", name: "Tokelau" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Türkiye" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TC", name: "Turks and Caicos Islands" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Viet Nam" },
  { code: "VG", name: "Virgin Islands, British" },
  { code: "VI", name: "Virgin Islands, U.S." },
  { code: "WF", name: "Wallis and Futuna" },
  { code: "EH", name: "Western Sahara" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
];

/** ISO 4217 tender used for display when adding a pricing region. Not stored
 *  on the user — checkout still reads currency/symbol from `Region`. */
export interface CountryTender {
  currency: string;
  symbol: string;
}

const TENDER_BY_CODE: Record<string, CountryTender> = {
  AD: { currency: "EUR", symbol: "€" },
  AE: { currency: "AED", symbol: "د.إ" },
  AF: { currency: "AFN", symbol: "؋" },
  AG: { currency: "XCD", symbol: "$" },
  AI: { currency: "XCD", symbol: "$" },
  AL: { currency: "ALL", symbol: "L" },
  AM: { currency: "AMD", symbol: "֏" },
  AO: { currency: "AOA", symbol: "Kz" },
  AR: { currency: "ARS", symbol: "$" },
  AS: { currency: "USD", symbol: "$" },
  AT: { currency: "EUR", symbol: "€" },
  AU: { currency: "AUD", symbol: "A$" },
  AW: { currency: "AWG", symbol: "ƒ" },
  AX: { currency: "EUR", symbol: "€" },
  AZ: { currency: "AZN", symbol: "₼" },
  BA: { currency: "BAM", symbol: "KM" },
  BB: { currency: "BBD", symbol: "$" },
  BD: { currency: "BDT", symbol: "৳" },
  BE: { currency: "EUR", symbol: "€" },
  BF: { currency: "XOF", symbol: "CFA" },
  BG: { currency: "EUR", symbol: "€" },
  BH: { currency: "BHD", symbol: "BD" },
  BI: { currency: "BIF", symbol: "FBu" },
  BJ: { currency: "XOF", symbol: "CFA" },
  BL: { currency: "EUR", symbol: "€" },
  BM: { currency: "BMD", symbol: "$" },
  BN: { currency: "BND", symbol: "$" },
  BO: { currency: "BOB", symbol: "Bs." },
  BR: { currency: "BRL", symbol: "R$" },
  BS: { currency: "BSD", symbol: "$" },
  BT: { currency: "BTN", symbol: "Nu." },
  BV: { currency: "NOK", symbol: "kr" },
  BW: { currency: "BWP", symbol: "P" },
  BY: { currency: "BYN", symbol: "Br" },
  BZ: { currency: "BZD", symbol: "$" },
  CA: { currency: "CAD", symbol: "C$" },
  CC: { currency: "AUD", symbol: "A$" },
  CD: { currency: "CDF", symbol: "FC" },
  CF: { currency: "XAF", symbol: "FCFA" },
  CG: { currency: "XAF", symbol: "FCFA" },
  CH: { currency: "CHF", symbol: "CHF" },
  CI: { currency: "XOF", symbol: "CFA" },
  CK: { currency: "NZD", symbol: "NZ$" },
  CL: { currency: "CLP", symbol: "$" },
  CM: { currency: "XAF", symbol: "FCFA" },
  CN: { currency: "CNY", symbol: "¥" },
  CO: { currency: "COP", symbol: "$" },
  CR: { currency: "CRC", symbol: "₡" },
  CU: { currency: "CUP", symbol: "$" },
  CV: { currency: "CVE", symbol: "$" },
  CW: { currency: "XCG", symbol: "Cg" },
  CX: { currency: "AUD", symbol: "A$" },
  CY: { currency: "EUR", symbol: "€" },
  CZ: { currency: "CZK", symbol: "Kč" },
  DE: { currency: "EUR", symbol: "€" },
  DJ: { currency: "DJF", symbol: "Fdj" },
  DK: { currency: "DKK", symbol: "kr" },
  DM: { currency: "XCD", symbol: "$" },
  DO: { currency: "DOP", symbol: "$" },
  DZ: { currency: "DZD", symbol: "DA" },
  EC: { currency: "USD", symbol: "$" },
  EE: { currency: "EUR", symbol: "€" },
  EG: { currency: "EGP", symbol: "E£" },
  EH: { currency: "MAD", symbol: "د.م." },
  ER: { currency: "ERN", symbol: "Nfk" },
  ES: { currency: "EUR", symbol: "€" },
  ET: { currency: "ETB", symbol: "Br" },
  FI: { currency: "EUR", symbol: "€" },
  FJ: { currency: "FJD", symbol: "$" },
  FK: { currency: "FKP", symbol: "£" },
  FM: { currency: "USD", symbol: "$" },
  FO: { currency: "DKK", symbol: "kr" },
  FR: { currency: "EUR", symbol: "€" },
  GA: { currency: "XAF", symbol: "FCFA" },
  GB: { currency: "GBP", symbol: "£" },
  GD: { currency: "XCD", symbol: "$" },
  GE: { currency: "GEL", symbol: "₾" },
  GF: { currency: "EUR", symbol: "€" },
  GG: { currency: "GBP", symbol: "£" },
  GH: { currency: "GHS", symbol: "₵" },
  GI: { currency: "GIP", symbol: "£" },
  GL: { currency: "DKK", symbol: "kr" },
  GM: { currency: "GMD", symbol: "D" },
  GN: { currency: "GNF", symbol: "FG" },
  GP: { currency: "EUR", symbol: "€" },
  GQ: { currency: "XAF", symbol: "FCFA" },
  GR: { currency: "EUR", symbol: "€" },
  GS: { currency: "GBP", symbol: "£" },
  GT: { currency: "GTQ", symbol: "Q" },
  GU: { currency: "USD", symbol: "$" },
  GW: { currency: "XOF", symbol: "CFA" },
  GY: { currency: "GYD", symbol: "$" },
  HK: { currency: "HKD", symbol: "HK$" },
  HM: { currency: "AUD", symbol: "A$" },
  HN: { currency: "HNL", symbol: "L" },
  HR: { currency: "EUR", symbol: "€" },
  HT: { currency: "HTG", symbol: "G" },
  HU: { currency: "HUF", symbol: "Ft" },
  ID: { currency: "IDR", symbol: "Rp" },
  IE: { currency: "EUR", symbol: "€" },
  IL: { currency: "ILS", symbol: "₪" },
  IM: { currency: "GBP", symbol: "£" },
  IN: { currency: "INR", symbol: "₹" },
  IO: { currency: "USD", symbol: "$" },
  IQ: { currency: "IQD", symbol: "ع.د" },
  IR: { currency: "IRR", symbol: "﷼" },
  IS: { currency: "ISK", symbol: "kr" },
  IT: { currency: "EUR", symbol: "€" },
  JE: { currency: "GBP", symbol: "£" },
  JM: { currency: "JMD", symbol: "$" },
  JO: { currency: "JOD", symbol: "JD" },
  JP: { currency: "JPY", symbol: "¥" },
  KE: { currency: "KES", symbol: "KSh" },
  KG: { currency: "KGS", symbol: "сом" },
  KH: { currency: "KHR", symbol: "៛" },
  KI: { currency: "AUD", symbol: "A$" },
  KM: { currency: "KMF", symbol: "CF" },
  KN: { currency: "XCD", symbol: "$" },
  KP: { currency: "KPW", symbol: "₩" },
  KR: { currency: "KRW", symbol: "₩" },
  KW: { currency: "KWD", symbol: "KD" },
  KY: { currency: "KYD", symbol: "$" },
  KZ: { currency: "KZT", symbol: "₸" },
  LA: { currency: "LAK", symbol: "₭" },
  LB: { currency: "LBP", symbol: "ل.ل" },
  LC: { currency: "XCD", symbol: "$" },
  LI: { currency: "CHF", symbol: "CHF" },
  LK: { currency: "LKR", symbol: "Rs" },
  LR: { currency: "LRD", symbol: "$" },
  LS: { currency: "LSL", symbol: "L" },
  LT: { currency: "EUR", symbol: "€" },
  LU: { currency: "EUR", symbol: "€" },
  LV: { currency: "EUR", symbol: "€" },
  LY: { currency: "LYD", symbol: "LD" },
  MA: { currency: "MAD", symbol: "د.م." },
  MC: { currency: "EUR", symbol: "€" },
  MD: { currency: "MDL", symbol: "L" },
  ME: { currency: "EUR", symbol: "€" },
  MF: { currency: "EUR", symbol: "€" },
  MG: { currency: "MGA", symbol: "Ar" },
  MH: { currency: "USD", symbol: "$" },
  MK: { currency: "MKD", symbol: "ден" },
  ML: { currency: "XOF", symbol: "CFA" },
  MM: { currency: "MMK", symbol: "K" },
  MN: { currency: "MNT", symbol: "₮" },
  MO: { currency: "MOP", symbol: "MOP$" },
  MP: { currency: "USD", symbol: "$" },
  MQ: { currency: "EUR", symbol: "€" },
  MR: { currency: "MRU", symbol: "UM" },
  MS: { currency: "XCD", symbol: "$" },
  MT: { currency: "EUR", symbol: "€" },
  MU: { currency: "MUR", symbol: "₨" },
  MV: { currency: "MVR", symbol: "Rf" },
  MW: { currency: "MWK", symbol: "MK" },
  MX: { currency: "MXN", symbol: "MX$" },
  MY: { currency: "MYR", symbol: "RM" },
  MZ: { currency: "MZN", symbol: "MT" },
  NA: { currency: "NAD", symbol: "N$" },
  NC: { currency: "XPF", symbol: "₣" },
  NE: { currency: "XOF", symbol: "CFA" },
  NF: { currency: "AUD", symbol: "A$" },
  NG: { currency: "NGN", symbol: "₦" },
  NI: { currency: "NIO", symbol: "C$" },
  NL: { currency: "EUR", symbol: "€" },
  NO: { currency: "NOK", symbol: "kr" },
  NP: { currency: "NPR", symbol: "₨" },
  NR: { currency: "AUD", symbol: "A$" },
  NU: { currency: "NZD", symbol: "NZ$" },
  NZ: { currency: "NZD", symbol: "NZ$" },
  OM: { currency: "OMR", symbol: "ر.ع." },
  PA: { currency: "PAB", symbol: "B/." },
  PE: { currency: "PEN", symbol: "S/" },
  PF: { currency: "XPF", symbol: "₣" },
  PG: { currency: "PGK", symbol: "K" },
  PH: { currency: "PHP", symbol: "₱" },
  PK: { currency: "PKR", symbol: "₨" },
  PL: { currency: "PLN", symbol: "zł" },
  PM: { currency: "EUR", symbol: "€" },
  PN: { currency: "NZD", symbol: "NZ$" },
  PR: { currency: "USD", symbol: "$" },
  PS: { currency: "ILS", symbol: "₪" },
  PT: { currency: "EUR", symbol: "€" },
  PW: { currency: "USD", symbol: "$" },
  PY: { currency: "PYG", symbol: "₲" },
  QA: { currency: "QAR", symbol: "ر.ق" },
  RE: { currency: "EUR", symbol: "€" },
  RO: { currency: "RON", symbol: "lei" },
  RS: { currency: "RSD", symbol: "дин" },
  RU: { currency: "RUB", symbol: "₽" },
  RW: { currency: "RWF", symbol: "FRw" },
  SA: { currency: "SAR", symbol: "ر.س" },
  SB: { currency: "SBD", symbol: "$" },
  SC: { currency: "SCR", symbol: "₨" },
  SD: { currency: "SDG", symbol: "ج.س." },
  SE: { currency: "SEK", symbol: "kr" },
  SG: { currency: "SGD", symbol: "S$" },
  SH: { currency: "SHP", symbol: "£" },
  SI: { currency: "EUR", symbol: "€" },
  SJ: { currency: "NOK", symbol: "kr" },
  SK: { currency: "EUR", symbol: "€" },
  SL: { currency: "SLE", symbol: "Le" },
  SM: { currency: "EUR", symbol: "€" },
  SN: { currency: "XOF", symbol: "CFA" },
  SO: { currency: "SOS", symbol: "Sh" },
  SR: { currency: "SRD", symbol: "$" },
  SS: { currency: "SSP", symbol: "£" },
  ST: { currency: "STN", symbol: "Db" },
  SV: { currency: "USD", symbol: "$" },
  SX: { currency: "XCG", symbol: "Cg" },
  SY: { currency: "SYP", symbol: "£" },
  SZ: { currency: "SZL", symbol: "L" },
  TC: { currency: "USD", symbol: "$" },
  TD: { currency: "XAF", symbol: "FCFA" },
  TF: { currency: "EUR", symbol: "€" },
  TG: { currency: "XOF", symbol: "CFA" },
  TH: { currency: "THB", symbol: "฿" },
  TJ: { currency: "TJS", symbol: "ЅМ" },
  TK: { currency: "NZD", symbol: "NZ$" },
  TL: { currency: "USD", symbol: "$" },
  TM: { currency: "TMT", symbol: "m" },
  TN: { currency: "TND", symbol: "د.ت" },
  TO: { currency: "TOP", symbol: "T$" },
  TR: { currency: "TRY", symbol: "₺" },
  TT: { currency: "TTD", symbol: "$" },
  TV: { currency: "AUD", symbol: "A$" },
  TW: { currency: "TWD", symbol: "NT$" },
  TZ: { currency: "TZS", symbol: "TSh" },
  UA: { currency: "UAH", symbol: "₴" },
  UG: { currency: "UGX", symbol: "USh" },
  US: { currency: "USD", symbol: "$" },
  UY: { currency: "UYU", symbol: "$" },
  UZ: { currency: "UZS", symbol: "so'm" },
  VA: { currency: "EUR", symbol: "€" },
  VC: { currency: "XCD", symbol: "$" },
  VE: { currency: "VES", symbol: "Bs." },
  VG: { currency: "USD", symbol: "$" },
  VI: { currency: "USD", symbol: "$" },
  VN: { currency: "VND", symbol: "₫" },
  VU: { currency: "VUV", symbol: "Vt" },
  WF: { currency: "XPF", symbol: "₣" },
  WS: { currency: "WST", symbol: "T" },
  YE: { currency: "YER", symbol: "﷼" },
  YT: { currency: "EUR", symbol: "€" },
  ZA: { currency: "ZAR", symbol: "R" },
  ZM: { currency: "ZMW", symbol: "ZK" },
  ZW: { currency: "USD", symbol: "$" },
};

/** Display tender for a country code, when one is well-known. */
export function tenderFor(code: string): CountryTender | undefined {
  return TENDER_BY_CODE[code.toUpperCase()];
}

const BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]));

/** All supported ISO 3166-1 alpha-2 codes in this list. */
export const ISO_COUNTRY_CODES: ReadonlySet<string> = new Set(
  COUNTRIES.map((c) => c.code),
);

export function isIsoCountryCode(code: string): boolean {
  return ISO_COUNTRY_CODES.has(code.toUpperCase());
}

/** Resolve an ISO 3166-1 alpha-2 code to its English display name. */
export function nameFor(code: string): string | undefined {
  return BY_CODE.get(code.toUpperCase())?.name;
}

/** Convert an ISO 3166-1 alpha-2 code to its flag emoji. */
export function flagFor(code: string): string {
  const c = code.toUpperCase();
  if (!/^[A-Z]{2}$/.test(c)) return "";
  const A = 0x1f1e6;
  return String.fromCodePoint(
    A + c.charCodeAt(0) - 65,
    A + c.charCodeAt(1) - 65,
  );
}
